name: OpenSilver Build
on:
  push:
    branches:
      - develop
env:
  SHA8: "$(echo ${{ github.sha }} | cut -c1-8)"
jobs:
  OpenSilver-Build:
    runs-on: windows-latest
    steps:
      - uses: microsoft/setup-msbuild@v1.0.3
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Clone OpenSilver repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Restore teamdev.licenses
        run: 'echo "$TEAMDEV_LICENSE" > ./src/Simulator/Simulator/teamdev.licenses'
        shell: bash
        env:
          TEAMDEV_LICENSE: ${{secrets.TEAMDEV_LICENSE}}
      - name: Restore Packages
        run: |
          ./restore-packages-opensilver.bat
          nuget restore src/OpenSilver.sln -v quiet
      - name: Build Compiler
        run: msbuild src/Compiler/Compiler/Compiler.OpenSilver.csproj -p:Configuration=SL -clp:ErrorsOnly -restore
      - name: Copy Compiler Assemblies
        run: cp src/Compiler/Compiler/bin/OpenSilver/SL/OpenSilver.Compiler*dll src/packages/OpenSilver.1.0.0/tools/;
      - name: Build OpenSilver
        working-directory: build
        run: msbuild slnf/OpenSilver.slnf -p:Configuration=SL -clp:ErrorsOnly -restore
      - name: Format Package Version
        id: version
        run: echo "::set-output name=suffix::$(date +'%Y-%m-%d-%H%M%S')-${{ env.SHA8 }}"
      - name: Build Simulator
        working-directory: build
        run: msbuild slnf/OpenSilver.Simulator.slnf -p:Configuration=SL -clp:ErrorsOnly -p:PackageOutputPath="output/OpenSilver" -p:NuspecFile="nuspec/OpenSilver.Simulator.nuspec" -p:NuspecProperties=PackageVersion=1.0.0-private-${{ steps.version.outputs.suffix }}
      - name: Pack OpenSilver
        working-directory: build
        run: |
          mkdir temp; echo "OpenSilver 1.0.0-private-${{ steps.version.outputs.suffix }}" > temp/Version.txt
          nuget.exe pack nuspec\OpenSilver.nuspec -OutputDirectory "output/OpenSilver" -Properties "PackageId=OpenSilver;PackageVersion=1.0.0-private-${{ steps.version.outputs.suffix }};Configuration=SL;Target=OpenSilver"
      - name: Pack Simulator
        working-directory: build
        run: |
          echo "OpenSilver.Simulator 1.0.0-private-${{ steps.version.outputs.suffix }}" > temp/Version.txt
          msbuild -t:pack slnf/OpenSilver.Simulator.slnf -p:Configuration=SL -clp:ErrorsOnly -p:PackageOutputPath="D:\a\OpenSilver\OpenSilver\build\output\OpenSilver" -p:NuspecFile="D:\a\OpenSilver\OpenSilver\build\nuspec\OpenSilver.Simulator.nuspec" -p:NuspecBasePath="D:\a\OpenSilver\OpenSilver\build" -p:NuspecProperties=PackageVersion=1.0.0-private-${{ steps.version.outputs.suffix }}
      - uses: actions/upload-artifact@v2
        with:
          name: OpenSilver
          path: "build/output/OpenSilver"